config/routes.rb
Rails.application.routes.draw do
  
  resources :comments
  get 'pages/about'

  get 'pages/contact'

  get 'pages/resources'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :posts 
  resources :categories 
  
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'resources', to: 'pages#resources'

  get 'categories/show'

  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :posts 
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post

  validates :name,  presence: true, length: { maximum: 20 }
  validates :body,  presence: true 
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :category 
	belongs_to :admin_user
	has_many :comments, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :all_categories
  helper_method :all_posts
  before_filter :site_search
  
  def all_categories
  	@categories = Category.all
  end
  def all_posts
  	@posts = Post.all
  end

  def site_search
   @q= Post.ransack(params[:q])
   @q_posts=@q.result(distinct: true)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController 

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @title = @category.name
    @posts = @category.posts 
  end

end

app/controllers/comments_controller.rb
class CommentsController < InheritedResources::Base

  
 def create
  	@comment = Comment.new(comment_params)
  	
  	if @comment.save
  		flash[:notice] = "Successful Comment"
  		redirect_to(@comment.post)
  	else
  		flash[:notice] = "Error creating comment: #{@comment.errors}"
  		redirect_to(@comment.post)

  	end
  end	
  private

    def comment_params
      params.require(:comment).permit(:name, :email, :body, :post_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
  	@posts = Post.all.order("created_at DESC")
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end

  def resources
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def index
		 @q= Post.ransack(params[:q])
   		 @posts=@q.result(distinct: true).order("created_at DESC")
	end

	def new
		@post = Post.new
		@category = Category.all 
	end

	def create
		@post = Post.new(post_params)
		if @post.save
			redirect_to posts_path, :notice => "Your post has been saved"
		else
			render "new"
		end 

	end

	def edit
		@post = Post.find(params[:id])
	end

	def update	
		@post = Post.find(params[:id])
		if @post.update_attributes(post_params)
			redirect_to post_path, :notice => "Your post has been updated"
		else
			render "edit"
		end 

	end

	def show
		@post = Post.find(params[:id])
		@user = AdminUser.all
		@comment= Comment.new(:post => @post)
	end

	def destroy	
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to posts_path, :notice => "Your post has been deleted"
	end

	private
		 def post_params
		      params.require(:post).permit(:title, :body, :category_id, :author_id)
		 
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/index.html.erb
<div class="post">
    <h1>Categories</h1>
    <ul>
      <% @categories.each do |category| %>
      <li><%= link_to category.name,category %></li>
      <% end %>
    </ul>
</div>

app/views/categories/show.html.erb
<% if @posts.each do |post| %>
<div class="post">
<h2 class="title"><%= link_to post.title,post %></h2>
	<div class="entry"><%= post.body %></div>
	   <div class="byline">
        <p class="meta">May 07, 2012 Posted by <a href="#">Someone</a></p>
        <p class="links"><a href="post.html">Read More</a> | <a href="post.html">Comments</a></p>
       </div>
	</div>
<% end.empty? %>
	<p style="color:white;">Sorry, no posts in this category</p>
<% end %>

app/views/home/index.html.erb
<% @posts.each do |post| %>
<div class="post">
<h2 class="title"><%= link_to post.title,post %></h2>
	<div class="entry"><%= post.body %></div>
	   <div class="byline">
        <p class="meta">May 07, 2012 Posted by <%= post.admin_user.name %></p>
        <p class="links"><%= link_to "Read More",post %> | <%= link_to "Comment",post %></p>
       </div>
	</div>
<% end %>

app/views/layouts/application.html.erb
<%= render "partials/header" %>
  <div id="page">
   <div id="page-bgtop">
    <div id="page-bgbtm">
     <div id="content">
    <div class="flash-message">
    <% flash.each do |key,value| %>
    <p><%= value %></p>
    <% end %>
    </div>
     <%= yield %><!--main view-->

      
      <div style="clear: both;"></div>
     </div><br>
     <!-- end #content -->
  
     <%= render "partials/sidebar" %>
     

    </div>
   </div>
  </div>
  <!-- end #page-->
  <div id="footer">
   <p>2013, My Ruby Blog - Sample Project</p>
  </div>
  <!-- en #footer-->
 </div>
 <!-- end #wrapper-->

  </body>
</html>

app/views/pages/about.html.erb
<div class="post"><h1>About Blog By Zaman</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec felis pulvinar augue porta egestas sed a purus. Quisque vehicula ultricies tortor. Phasellus et justo quis justo suscipit vestibulum. Maecenas at consequat lorem, ac blandit sem. In dignissim, risus non convallis bibendum, nisl sapien semper sapien, ac rhoncus nisi urna sit amet nulla. Duis vitae eleifend velit. Vestibulum commodo velit at nunc convallis congue. Phasellus molestie vestibulum justo non tincidunt. Sed arcu mauris, sodales a neque ac, sollicitudin euismod ex. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>

<p>Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur sit amet viverra purus. Nam efficitur tortor vitae risus congue lobortis. Nunc sollicitudin sem ac felis pulvinar pretium. Nulla vel vehicula felis. Cras vitae dolor justo. Maecenas dolor tellus, tempus id aliquam eget, iaculis non ante. Vivamus dictum velit sit amet tortor fringilla, quis vulputate lectus commodo.</p>

<p>Donec id tincidunt lacus, sed dictum nunc. Cras in sem dui. Duis non gravida arcu. Nulla sed odio purus. Etiam dignissim viverra porta. Nulla id purus odio. Integer lacus orci, elementum ut faucibus a, pharetra quis elit. In ut ornare est. Donec ut turpis a lorem tincidunt aliquam ut nec velit.</p>
</div>

app/views/pages/contact.html.erb
<div class="post"><h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>
</div>

app/views/pages/resources.html.erb
<div class="post"><h1>Pages#resources</h1>
<p>Find me in app/views/pages/resources.html.erb</p>
</div>

app/views/partials/_comment.html.erb
<div class="comment">
	<i><%=h comment.name %> says:</i><br>
	<%= simple_format h(comment.body) %>
</div>

app/views/partials/_header.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog By Zaman</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Abel" type="text/css" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
 <div id="wrapper">
  <div id="header-wrapper">
   <div id="header1">
    <div id="logo">
     <h1><a href="#">Blog By Zaman</a></h1>
     <p>Learing Ruby on Rails</p>
    </div>
    <div id="menu">
      <ul class="main-nav">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "About", about_path %></li>
          <li><%= link_to "Blog", posts_path %></li>
          <li><%= link_to "Contact", contact_path %></li>
          <li><%= link_to "Resources", resources_path %></li>
        
      </ul>

  </div>

   </div>
  </div>
  <!-- end #header -->

app/views/partials/_sidebar.html.erb
<div id="sidebar">
      <ul>
       <li>
        <div id="search">
            <%= search_form_for @q do |f| %>
            <%= f.text_field :title_or_body_contains %>
            <%= f.submit "Search" %>
            <% end %>
        </div>﻿<br>
        <div style="clear: both;"></div>
       </li>
       <li>
        <h2>Get The Framework</h2>
        <p>You can download Ruby and/or Ruby on Rails for free right now
         <br>
         <a style="color:#D93544" href="http://rubyonrails.org/download"></a></p>
       </li>
       <li>
        <h2>Categories</h2>
        <ul>
          <% all_categories.each do |cat| %>
            <li><%= link_to cat.name,category_path(:id => cat.id) %></li>
         <% end %>
          
        </ul>
       </li><br>
       <li>
        <h2>Blogroll</h2>
        <ul>
          <% all_posts.each do |post| %>
            <li><%= link_to post.title,post_path(:id => post.id) %></li>
          <% end %>
        </ul>
       </li>

      </ul>
     </div>
     <!-- end #sidebar -->

app/views/posts/index.html.erb
<% @posts.each do |post| %>
<div class="post">
<h2 class="title"><%= link_to post.title,post %></h2>
	<div class="entry"><%= post.body %></div>
	   <div class="byline">
        <p class="meta">May 07, 2012 Posted by <%= post.admin_user.name %></p>
        <p class="links"><%= link_to "Read More",post %> | <%= link_to "Comment",post %></p>
       </div>
	</div>
<% end %>

app/views/posts/show.html.erb
<div class="post">
<h1><%= @post.title %></h1>
<small><%= @post.created_at.strftime("%b %d. %Y") %></small>
<p>Created By: <%= @post.admin_user.name %>
<p><%= @post.body %></p>
<p>Category: <%= link_to @post.category.name,category_path(:id => @post.category.id) %></p>
<p><%= link_to "Back",posts_path %></p>
<hr>
<h3>Add a comment</h3>
<%= form_for @comment do |f| %>
	<%= f.hidden_field :post_id %>

	<p>
	<%= f.label :name %><br>
	<%= f.text_field :name %>
	</p> 

	<p>
	<%= f.label :email %><br>
	<%= f.text_field :email %>
	</p> 

	<p>
	<%= f.label :body %><br>
	<%= f.text_area :body %>
	</p> 

	<p>
	<%= f.submit "Post comment" %>
	</p> 

<% end %>
<br>
<%= render :partial => 'partials/comment', :collection => @post.comments %>
</div>